version: '3.9'
services:
  mariadb:
    image: bitnami/mariadb:10.6
    networks:
      - moodle-prod
    restart: always
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=PkCr#1
      - MARIADB_ROOT_PASSWORD=PkCr#1
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_moodle_prod_data:/bitnami/mariadb'
  moodle:
    image: bitnami/moodle:4.2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.moodle.rule=Host(`{{server}}`)"
      - "traefik.http.routers.moodle.entrypoints=web,websecure"
      - "traefik.http.routers.moodle.tls.certresolver=myresolver"
      - "traefik.http.services.moodle.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.moodle.middlewares=redirect-to-https"
    networks:
      - moodle-prod
      - proxy-network
    restart: always
    environment:
      - BITNAMI_DEBUG=false
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_DATABASE_PASSWORD=PkCr#1
      - MOODLE_DATABASE_ROOT_PASSWORD=PkCr#1
      - MOODLE_SITE_NAME=Capacitacion Asesoria Alimentos
      - MOODLE_USERNAME=david
      - MOODLE_PASSWORD=PkCr
      - MOODLE_URL={{server}}
    volumes:
      - 'moodle_prod_data:/bitnami/moodle'
      - 'moodledata_prod_data:/bitnami/moodledata'
    depends_on:
      - mariadb
volumes:
  mariadb_moodle_prod_data:
    driver: local
  moodle_prod_data:
    driver: local
  moodledata_prod_data:
    driver: local

networks:
    moodle-prod:
    proxy-network:
        external: true