---
- hosts: villarreal
  become: yes
  tasks:
    - name: Ensure docker is installed
      apt:
        name: docker
        state: present
        update_cache: yes

    - name: Ensure network exists
      command: docker network create proxy-network
      register: network_result
      failed_when: network_result.rc != 0 and 'already exists' not in network_result.stderr

    - name: Ensure traefik is running
      shell:
        cmd: "docker compose -f /home/ubuntu/apps/traefik/traefik.yml up -d"
        chdir: /home/ubuntu/apps/traefik/

    - name: Ensure other docker-compose projects are running
      shell:
        cmd: "docker compose -f {{ item }} up -d"
        chdir: /home/ubuntu/apps/
      loop:
        - moodle/moodle.yml
        - bienesraices/bienesraices.yml
        - nextcloud/nextcloud.yml
...
