  
version: '3'

services:
  bienes-raices-web:
    image: wyveo/nginx-php-fpm:php81
    restart: always
    expose:
      - "80"
    networks:
      - proxy-network
    volumes:
      - /home/ubuntu/www/bienesraices:/usr/share/nginx/html:ro
    environment:
        #for other proxy
      - VIRTUAL_HOST=bienesraices.{{server}}.net
      - LETSENCRYPT_HOST=bienesraices.{{server}}.net
      - LETSENCRYPT_EMAIL=user@mail.com
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bienes-raices-web.rule=Host(`{{servercg}}.com`)"
      - "traefik.http.routers.bienes-raices-web.entrypoints=websecure"
      - "traefik.http.routers.bienes-raices-web.tls.certresolver=myresolver"
      - "traefik.http.services.bienes-raices-web.loadbalancer.server.port=80"

networks:
  proxy-network:
    external: true