version: '3.8'

services:
  nextcloud:
    image: nextcloud:27.0.0-apache
    container_name: nextcloud
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_NEXTCLOUD_PASSWORD}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_TRUSTED_DOMAINS=dropbox.{{server}}.net
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_KEY}
      - OBJECT_STORAGE=s3
      - OBJECT_STORAGE_BUCKET=dropbox-villarreal
        #- OBJECT_STORAGE_AUTOCREATE=true
      - TRUSTED_PROXIES=172.22.0.0/16
    volumes:
      - nextcloud_data:/var/www/html
    depends_on:
      - db
    networks:
      - nextcloud_network
      - proxy-network
    restart: always
    labels:

      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.rule=Host(`dropbox.{{server}}.net`)"
      - "traefik.http.routers.nextcloud.tls.certresolver=myresolver"
        #- "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.nextcloud.middlewares=redirect-to-https"

  db:
    image: mariadb:10.6
    container_name: nextcloud_db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_NEXTCLOUD_PASSWORD}
    volumes:
      - db_nextcloud_demo:/var/lib/mysql
    networks:
      - nextcloud_network
    restart: always

networks:
  nextcloud_network:
  proxy-network:
    external: true

volumes:
  nextcloud_data:
  db_nextcloud_demo:
