version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`${SERVER}`)"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.tls.certresolver=myresolver"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      - "traefik.http.services.n8n.loadbalancer.server.scheme=http"

      # Enable WebSockets
      - "traefik.http.middlewares.n8n-websockets.headers.customrequestheaders.Upgrade=websocket"
      - "traefik.http.middlewares.n8n-websockets.headers.customrequestheaders.Connection=Upgrade"
      - "traefik.http.routers.n8n.middlewares=n8n-websockets@docker"
    
    networks:
      - proxy-network
    restart: unless-stopped
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${USER}  # from .env file
      - N8N_BASIC_AUTH_PASSWORD=${PASSWORD}  # from .env file
      - N8N_HOST=${SERVER}
      - N8N_PROTOCOL=https
      - N8N_PORT=5678
      - DB_TYPE=sqlite
      - N8N_EDITOR_BASE_URL=https://`${SERVER}`
      - WEBHOOK_TUNNEL_URL=https://`${SERVER}`/
      - WEBHOOK_URL=https://`${SERVER}`/ # Ensures webhooks are correctly resolved
    ports:
      - 5678:5678
    volumes:
      - n8n_storage:/home/node/.n8n

networks:
  proxy-network:
    external: true

volumes:
  n8n_storage:
    external: true
